version: '3.8'

services:
  notification-service:
    build: ./notification-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  analytics-service:
    build: ./analytics-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped