name: CI/CD Pipeline for Flower Shop

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    # ДОБАВЬ ЭТУ ПРОВЕРКУ:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4
      
      - name: Check if backend exists
        id: check_backend
        run: |
          if [ -f "backend/package.json" ]; then
            echo "backend_exists=true" >> $GITHUB_OUTPUT
          else
            echo "backend_exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Setup Node.js
        if: steps.check_backend.outputs.backend_exists == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Install Backend Dependencies
        if: steps.check_backend.outputs.backend_exists == 'true'
        run: npm ci

      - name: Run Linter for Backend
        if: steps.check_backend.outputs.backend_exists == 'true'
        run: npm run lint || echo "No lint script found"

  frontend-test:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'skip ci') == false
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      
      - name: Check if frontend exists
        id: check_frontend  
        run: |
          if [ -f "frontend/package.json" ]; then
            echo "frontend_exists=true" >> $GITHUB_OUTPUT
          else
            echo "frontend_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node.js
        if: steps.check_frontend.outputs.frontend_exists == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Frontend Dependencies
        if: steps.check_frontend.outputs.frontend_exists == 'true'
        run: npm ci

      - name: Run Linter for Frontend
        if: steps.check_frontend.outputs.frontend_exists == 'true'
        run: npm run lint || echo "No lint script found"

      - name: Check Build for Frontend
        if: steps.check_frontend.outputs.frontend_exists == 'true'
        run: npm run build || echo "No build script found"
