name: CI/CD Pipeline for Flower Shop

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  validate-structure:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate Project Structure
        run: |
          echo "🔍 Checking project structure..."
          echo "Current directory: $(pwd)"
          echo "Files in root:"
          ls -la
          
          if [ -f "README.md" ]; then
            echo "✅ README.md exists"
          else
            echo "❌ README.md missing"
          fi
          
          if [ -d ".github/workflows" ]; then
            echo "✅ GitHub Actions workflow exists"
          else
            echo "❌ GitHub Actions workflow missing"
          fi
          
          echo "🎉 Basic validation passed!"

  backend-setup:
    runs-on: ubuntu-latest
    needs: validate-structure
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Check Node.js version
        run: node --version

  frontend-setup:
    runs-on: ubuntu-latest
    needs: validate-structure
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Check npm version
        run: npm --version
